
package com.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ApplicationService", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApplicationService {


    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetApplicationDetailServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplicationDetail", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationDetail")
    @ResponseWrapper(localName = "getApplicationDetailResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationDetailResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationDetailRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationDetailResponse")
    public GetApplicationDetailServiceResponse getApplicationDetail(
        @WebParam(name = "request", targetNamespace = "")
        GetApplicationDetailServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.MarkAsOnHoldApplicationServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "markAsOnHoldApplication", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.MarkAsOnHoldApplication")
    @ResponseWrapper(localName = "markAsOnHoldApplicationResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.MarkAsOnHoldApplicationResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/markAsOnHoldApplicationRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/markAsOnHoldApplicationResponse")
    public MarkAsOnHoldApplicationServiceResponse markAsOnHoldApplication(
        @WebParam(name = "request", targetNamespace = "")
        MarkAsOnHoldApplicationServiceRequest request);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.service.BiometricDataResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBiometricData", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetBiometricData")
    @ResponseWrapper(localName = "getBiometricDataResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetBiometricDataResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getBiometricDataRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getBiometricDataResponse")
    public BiometricDataResponse getBiometricData(
        @WebParam(name = "arg0", targetNamespace = "")
        BiometricDataRequest arg0);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.AdjudcationPanelInfoServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "viewAdjudicationPanelInfo", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.ViewAdjudicationPanelInfo")
    @ResponseWrapper(localName = "viewAdjudicationPanelInfoResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.ViewAdjudicationPanelInfoResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/viewAdjudicationPanelInfoRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/viewAdjudicationPanelInfoResponse")
    public AdjudcationPanelInfoServiceResponse viewAdjudicationPanelInfo(
        @WebParam(name = "request", targetNamespace = "")
        AdjudcationPanelInfoServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.util.List<com.service.AdjudicationPanelInfoResponse>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAdjudicationPanelInfo", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetAdjudicationPanelInfo")
    @ResponseWrapper(localName = "getAdjudicationPanelInfoResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetAdjudicationPanelInfoResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getAdjudicationPanelInfoRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getAdjudicationPanelInfoResponse")
    public List<AdjudicationPanelInfoResponse> getAdjudicationPanelInfo(
        @WebParam(name = "request", targetNamespace = "")
        AdjudicationPanelInfoRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetPersonBiometricInfoServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonBiometricInfo", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetPersonBiometricInfo")
    @ResponseWrapper(localName = "getPersonBiometricInfoResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetPersonBiometricInfoResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getPersonBiometricInfoRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getPersonBiometricInfoResponse")
    public GetPersonBiometricInfoServiceResponse getPersonBiometricInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetPersonBiometricInfoServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetApplicationCountByAuthorityServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplicationCountByAuthority", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationCountByAuthority")
    @ResponseWrapper(localName = "getApplicationCountByAuthorityResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationCountByAuthorityResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationCountByAuthorityRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationCountByAuthorityResponse")
    public GetApplicationCountByAuthorityServiceResponse getApplicationCountByAuthority(
        @WebParam(name = "request", targetNamespace = "")
        GetApplicationCountByAuthorityServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetApplicationCountByStatusServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplicationCountByStatus", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationCountByStatus")
    @ResponseWrapper(localName = "getApplicationCountByStatusResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationCountByStatusResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationCountByStatusRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationCountByStatusResponse")
    public GetApplicationCountByStatusServiceResponse getApplicationCountByStatus(
        @WebParam(name = "request", targetNamespace = "")
        GetApplicationCountByStatusServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.UpdateApplicationStatusServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateApplicationStatus", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.UpdateApplicationStatus")
    @ResponseWrapper(localName = "updateApplicationStatusResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.UpdateApplicationStatusResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/updateApplicationStatusRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/updateApplicationStatusResponse")
    public UpdateApplicationStatusServiceResponse updateApplicationStatus(
        @WebParam(name = "request", targetNamespace = "")
        UpdateApplicationStatusServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetApplicationCountSummaryServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplicationCountSummary", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationCountSummary")
    @ResponseWrapper(localName = "getApplicationCountSummaryResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationCountSummaryResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationCountSummaryRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationCountSummaryResponse")
    public GetApplicationCountSummaryServiceResponse getApplicationCountSummary(
        @WebParam(name = "request", targetNamespace = "")
        GetApplicationCountSummaryServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetApplicationStatusHistoryServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplicationStatusHistory", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationStatusHistory")
    @ResponseWrapper(localName = "getApplicationStatusHistoryResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationStatusHistoryResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationStatusHistoryRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationStatusHistoryResponse")
    public GetApplicationStatusHistoryServiceResponse getApplicationStatusHistory(
        @WebParam(name = "request", targetNamespace = "")
        GetApplicationStatusHistoryServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.SetVipApplicationServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setVipApplication", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.SetVipApplication")
    @ResponseWrapper(localName = "setVipApplicationResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.SetVipApplicationResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/setVipApplicationRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/setVipApplicationResponse")
    public SetVipApplicationServiceResponse setVipApplication(
        @WebParam(name = "request", targetNamespace = "")
        SetVipApplicationServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.MarkAsVipApplicationServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "markAsVipApplication", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.MarkAsVipApplication")
    @ResponseWrapper(localName = "markAsVipApplicationResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.MarkAsVipApplicationResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/markAsVipApplicationRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/markAsVipApplicationResponse")
    public MarkAsVipApplicationServiceResponse markAsVipApplication(
        @WebParam(name = "request", targetNamespace = "")
        MarkAsVipApplicationServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.SuspendApplicationServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "suspendApplication", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.SuspendApplication")
    @ResponseWrapper(localName = "suspendApplicationResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.SuspendApplicationResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/suspendApplicationRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/suspendApplicationResponse")
    public SuspendApplicationServiceResponse suspendApplication(
        @WebParam(name = "request", targetNamespace = "")
        SuspendApplicationServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.RestoreApplicationServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "restoreApplication", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.RestoreApplication")
    @ResponseWrapper(localName = "restoreApplicationResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.RestoreApplicationResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/restoreApplicationRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/restoreApplicationResponse")
    public RestoreApplicationServiceResponse restoreApplication(
        @WebParam(name = "request", targetNamespace = "")
        RestoreApplicationServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.EditApplicationServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editApplication", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EditApplication")
    @ResponseWrapper(localName = "editApplicationResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EditApplicationResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/editApplicationRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/editApplicationResponse")
    public EditApplicationServiceResponse editApplication(
        @WebParam(name = "request", targetNamespace = "")
        EditApplicationServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.EnrollRenewalAppServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enrollRenewalApp", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollRenewalApp")
    @ResponseWrapper(localName = "enrollRenewalAppResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollRenewalAppResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollRenewalAppRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollRenewalAppResponse")
    public EnrollRenewalAppServiceResponse enrollRenewalApp(
        @WebParam(name = "request", targetNamespace = "")
        EnrollRenewalAppServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.EnrollDuplicateAppServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enrollDuplicateApp", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollDuplicateApp")
    @ResponseWrapper(localName = "enrollDuplicateAppResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollDuplicateAppResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollDuplicateAppRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollDuplicateAppResponse")
    public EnrollDuplicateAppServiceResponse enrollDuplicateApp(
        @WebParam(name = "request", targetNamespace = "")
        EnrollDuplicateAppServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.EnrollVehicleClassChangeAppServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enrollVehicleClassChangeApp", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollVehicleClassChangeApp")
    @ResponseWrapper(localName = "enrollVehicleClassChangeAppResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollVehicleClassChangeAppResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollVehicleClassChangeAppRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollVehicleClassChangeAppResponse")
    public EnrollVehicleClassChangeAppServiceResponse enrollVehicleClassChangeApp(
        @WebParam(name = "request", targetNamespace = "")
        EnrollVehicleClassChangeAppServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.EnrollVehicleClassAddAppServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enrollVehicleClassAddApp", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollVehicleClassAddApp")
    @ResponseWrapper(localName = "enrollVehicleClassAddAppResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollVehicleClassAddAppResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollVehicleClassAddAppRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollVehicleClassAddAppResponse")
    public EnrollVehicleClassAddAppServiceResponse enrollVehicleClassAddApp(
        @WebParam(name = "request", targetNamespace = "")
        EnrollVehicleClassAddAppServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.EnrollPSVAppServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enrollPSVApp", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollPSVApp")
    @ResponseWrapper(localName = "enrollPSVAppResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollPSVAppResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollPSVAppRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollPSVAppResponse")
    public EnrollPSVAppServiceResponse enrollPSVApp(
        @WebParam(name = "request", targetNamespace = "")
        EnrollPSVAppServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.EnrollTypeChangeAppServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enrollTypeChangeApp", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollTypeChangeApp")
    @ResponseWrapper(localName = "enrollTypeChangeAppResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollTypeChangeAppResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollTypeChangeAppRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollTypeChangeAppResponse")
    public EnrollTypeChangeAppServiceResponse enrollTypeChangeApp(
        @WebParam(name = "request", targetNamespace = "")
        EnrollTypeChangeAppServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.UpdatePaymentInfoServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePaymentInfo", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.UpdatePaymentInfo")
    @ResponseWrapper(localName = "updatePaymentInfoResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.UpdatePaymentInfoResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/updatePaymentInfoRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/updatePaymentInfoResponse")
    public UpdatePaymentInfoServiceResponse updatePaymentInfo(
        @WebParam(name = "request", targetNamespace = "")
        UpdatePaymentInfoServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetApplicationStatusSummaryServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplicationStatusSummary", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationStatusSummary")
    @ResponseWrapper(localName = "getApplicationStatusSummaryResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationStatusSummaryResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationStatusSummaryRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationStatusSummaryResponse")
    public GetApplicationStatusSummaryServiceResponse getApplicationStatusSummary(
        @WebParam(name = "request", targetNamespace = "")
        GetApplicationStatusSummaryServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.AddEndorsementServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEndorsementApplication", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.AddEndorsementApplication")
    @ResponseWrapper(localName = "addEndorsementApplicationResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.AddEndorsementApplicationResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/addEndorsementApplicationRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/addEndorsementApplicationResponse")
    public AddEndorsementServiceResponse addEndorsementApplication(
        @WebParam(name = "request", targetNamespace = "")
        AddEndorsementServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.UpdateEndorsementServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEndorsementApplication", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.UpdateEndorsementApplication")
    @ResponseWrapper(localName = "updateEndorsementApplicationResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.UpdateEndorsementApplicationResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/updateEndorsementApplicationRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/updateEndorsementApplicationResponse")
    public UpdateEndorsementServiceResponse updateEndorsementApplication(
        @WebParam(name = "request", targetNamespace = "")
        UpdateEndorsementServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.SearchEndorsementServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchEndorsementApplication", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.SearchEndorsementApplication")
    @ResponseWrapper(localName = "searchEndorsementApplicationResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.SearchEndorsementApplicationResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/searchEndorsementApplicationRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/searchEndorsementApplicationResponse")
    public SearchEndorsementServiceResponse searchEndorsementApplication(
        @WebParam(name = "request", targetNamespace = "")
        SearchEndorsementServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetEndorsementDetailsServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEndorsementDetails", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetEndorsementDetails")
    @ResponseWrapper(localName = "getEndorsementDetailsResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetEndorsementDetailsResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getEndorsementDetailsRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getEndorsementDetailsResponse")
    public GetEndorsementDetailsServiceResponse getEndorsementDetails(
        @WebParam(name = "request", targetNamespace = "")
        GetEndorsementDetailsServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetDatabaseLogServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatabaseLogs", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetDatabaseLogs")
    @ResponseWrapper(localName = "getDatabaseLogsResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetDatabaseLogsResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getDatabaseLogsRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getDatabaseLogsResponse")
    public GetDatabaseLogServiceResponse getDatabaseLogs(
        @WebParam(name = "request", targetNamespace = "")
        GetDatabaseLogServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.EnrollCorrectionTypeApplicationResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enrollCorrectionTypeApp", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollCorrectionTypeApp")
    @ResponseWrapper(localName = "enrollCorrectionTypeAppResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollCorrectionTypeAppResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollCorrectionTypeAppRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollCorrectionTypeAppResponse")
    public EnrollCorrectionTypeApplicationResponse enrollCorrectionTypeApp(
        @WebParam(name = "request", targetNamespace = "")
        EnrollCorrectionTypeAppRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.EnrollEndorsementApplicationResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enrollEndorseApp", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollEndorseApp")
    @ResponseWrapper(localName = "enrollEndorseAppResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EnrollEndorseAppResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollEndorseAppRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/enrollEndorseAppResponse")
    public EnrollEndorsementApplicationResponse enrollEndorseApp(
        @WebParam(name = "request", targetNamespace = "")
        EnrollEndorsementApplicationRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetEndorsementApplicationServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEndorsementApplication", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetEndorsementApplication")
    @ResponseWrapper(localName = "getEndorsementApplicationResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetEndorsementApplicationResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getEndorsementApplicationRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getEndorsementApplicationResponse")
    public GetEndorsementApplicationServiceResponse getEndorsementApplication(
        @WebParam(name = "request", targetNamespace = "")
        GetEndorsementApplicationServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.ApplicationDetailsEditResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editApplicationDetails", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EditApplicationDetails")
    @ResponseWrapper(localName = "editApplicationDetailsResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.EditApplicationDetailsResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/editApplicationDetailsRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/editApplicationDetailsResponse")
    public ApplicationDetailsEditResponse editApplicationDetails(
        @WebParam(name = "request", targetNamespace = "")
        ApplicationDetailsEditRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetOldApplicationHistoryResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInactiveApplicationHistory", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetInactiveApplicationHistory")
    @ResponseWrapper(localName = "getInactiveApplicationHistoryResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetInactiveApplicationHistoryResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getInactiveApplicationHistoryRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getInactiveApplicationHistoryResponse")
    public GetOldApplicationHistoryResponse getInactiveApplicationHistory(
        @WebParam(name = "request", targetNamespace = "")
        GetOldApplicationHistoryRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetApplicationQAPendingAuthoritiesServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplicationQAPendingAuthorities", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationQAPendingAuthorities")
    @ResponseWrapper(localName = "getApplicationQAPendingAuthoritiesResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationQAPendingAuthoritiesResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationQAPendingAuthoritiesRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationQAPendingAuthoritiesResponse")
    public GetApplicationQAPendingAuthoritiesServiceResponse getApplicationQAPendingAuthorities(
        @WebParam(name = "request", targetNamespace = "")
        GetApplicationQAPendingAuthoritiesServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetApplicationIdServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplicationId", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationId")
    @ResponseWrapper(localName = "getApplicationIdResponse", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", className = "com.service.GetApplicationIdResponse")
    @Action(input = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationIdRequest", output = "http://bean.license.ws.service.hsdl.soa.tigerit.com/ApplicationService/getApplicationIdResponse")
    public GetApplicationIdServiceResponse getApplicationId(
        @WebParam(name = "request", targetNamespace = "")
        GetApplicationIdServiceRequest request);

}
