
package com.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ApplicationService", targetNamespace = "http://bean.license.ws.service.hsdl.soa.tigerit.com/", wsdlLocation = "http://192.168.1.31:7025/hsdl/ApplicationService?wsdl")
public class ApplicationService_Service
    extends Service
{

    private final static URL APPLICATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException APPLICATIONSERVICE_EXCEPTION;
    private final static QName APPLICATIONSERVICE_QNAME = new QName("http://bean.license.ws.service.hsdl.soa.tigerit.com/", "ApplicationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.31:7025/hsdl/ApplicationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APPLICATIONSERVICE_WSDL_LOCATION = url;
        APPLICATIONSERVICE_EXCEPTION = e;
    }

    public ApplicationService_Service() {
        super(__getWsdlLocation(), APPLICATIONSERVICE_QNAME);
    }

    public ApplicationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), APPLICATIONSERVICE_QNAME, features);
    }

    public ApplicationService_Service(URL wsdlLocation) {
        super(wsdlLocation, APPLICATIONSERVICE_QNAME);
    }

    public ApplicationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APPLICATIONSERVICE_QNAME, features);
    }

    public ApplicationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApplicationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ApplicationService
     */
    @WebEndpoint(name = "ApplicationServicePort")
    public ApplicationService getApplicationServicePort() {
        return super.getPort(new QName("http://bean.license.ws.service.hsdl.soa.tigerit.com/", "ApplicationServicePort"), ApplicationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApplicationService
     */
    @WebEndpoint(name = "ApplicationServicePort")
    public ApplicationService getApplicationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bean.license.ws.service.hsdl.soa.tigerit.com/", "ApplicationServicePort"), ApplicationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APPLICATIONSERVICE_EXCEPTION!= null) {
            throw APPLICATIONSERVICE_EXCEPTION;
        }
        return APPLICATIONSERVICE_WSDL_LOCATION;
    }

}
