
package com.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EnrollmentServiceBeanService", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", wsdlLocation = "http://192.168.1.31:7025/preenrollment/EnrollmentService?WSDL")
public class EnrollmentServiceBeanService_Service
    extends Service
{

    private final static URL ENROLLMENTSERVICEBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENROLLMENTSERVICEBEANSERVICE_EXCEPTION;
    private final static QName ENROLLMENTSERVICEBEANSERVICE_QNAME = new QName("http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", "EnrollmentServiceBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.31:7025/preenrollment/EnrollmentService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENROLLMENTSERVICEBEANSERVICE_WSDL_LOCATION = url;
        ENROLLMENTSERVICEBEANSERVICE_EXCEPTION = e;
    }

    public EnrollmentServiceBeanService_Service() {
        super(__getWsdlLocation(), ENROLLMENTSERVICEBEANSERVICE_QNAME);
    }

    public EnrollmentServiceBeanService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENROLLMENTSERVICEBEANSERVICE_QNAME, features);
    }

    public EnrollmentServiceBeanService_Service(URL wsdlLocation) {
        super(wsdlLocation, ENROLLMENTSERVICEBEANSERVICE_QNAME);
    }

    public EnrollmentServiceBeanService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENROLLMENTSERVICEBEANSERVICE_QNAME, features);
    }

    public EnrollmentServiceBeanService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnrollmentServiceBeanService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EnrollmentServiceBeanService
     */
    @WebEndpoint(name = "EnrollmentServicePort")
    public EnrollmentServiceBeanService getEnrollmentServicePort() {
        return super.getPort(new QName("http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", "EnrollmentServicePort"), EnrollmentServiceBeanService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnrollmentServiceBeanService
     */
    @WebEndpoint(name = "EnrollmentServicePort")
    public EnrollmentServiceBeanService getEnrollmentServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", "EnrollmentServicePort"), EnrollmentServiceBeanService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENROLLMENTSERVICEBEANSERVICE_EXCEPTION!= null) {
            throw ENROLLMENTSERVICEBEANSERVICE_EXCEPTION;
        }
        return ENROLLMENTSERVICEBEANSERVICE_WSDL_LOCATION;
    }

}
