
package com.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EnrollmentServiceBeanService", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnrollmentServiceBeanService {


    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetEnrollmentServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplication", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetApplication")
    @ResponseWrapper(localName = "getApplicationResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetApplicationResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getApplicationRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getApplicationResponse")
    public GetEnrollmentServiceResponse getApplication(
        @WebParam(name = "request", targetNamespace = "")
        GetApplicationServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetDistrictServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDistrict", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetDistrict")
    @ResponseWrapper(localName = "getDistrictResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetDistrictResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getDistrictRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getDistrictResponse")
    public GetDistrictServiceResponse getDistrict(
        @WebParam(name = "request", targetNamespace = "")
        GetDistrictServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.LoginServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.LoginResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/loginRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/loginResponse")
    public LoginServiceResponse login(
        @WebParam(name = "request", targetNamespace = "")
        LoginServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetEnrollmentServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "disableApplication", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.DisableApplication")
    @ResponseWrapper(localName = "disableApplicationResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.DisableApplicationResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/disableApplicationRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/disableApplicationResponse")
    public GetEnrollmentServiceResponse disableApplication(
        @WebParam(name = "request", targetNamespace = "")
        GetApplicationServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetAppointmentDateServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvailableAppointmentDates", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetAvailableAppointmentDates")
    @ResponseWrapper(localName = "getAvailableAppointmentDatesResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetAvailableAppointmentDatesResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getAvailableAppointmentDatesRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getAvailableAppointmentDatesResponse")
    public GetAppointmentDateServiceResponse getAvailableAppointmentDates(
        @WebParam(name = "request", targetNamespace = "")
        GetAppointmentDateServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.ApplicationUpdateServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changeExamDate", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.ChangeExamDate")
    @ResponseWrapper(localName = "changeExamDateResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.ChangeExamDateResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/changeExamDateRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/changeExamDateResponse")
    public ApplicationUpdateServiceResponse changeExamDate(
        @WebParam(name = "request", targetNamespace = "")
        ApplicationUpdateServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.UpdatePaymentStatusServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePaymentStatus", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.UpdatePaymentStatus")
    @ResponseWrapper(localName = "updatePaymentStatusResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.UpdatePaymentStatusResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/updatePaymentStatusRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/updatePaymentStatusResponse")
    public UpdatePaymentStatusServiceResponse updatePaymentStatus(
        @WebParam(name = "request", targetNamespace = "")
        UpdatePaymentStatusServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.UpdateDLPaymentStatusServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateDLPaymentStatus", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.UpdateDLPaymentStatus")
    @ResponseWrapper(localName = "updateDLPaymentStatusResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.UpdateDLPaymentStatusResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/updateDLPaymentStatusRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/updateDLPaymentStatusResponse")
    public UpdateDLPaymentStatusServiceResponse updateDLPaymentStatus(
        @WebParam(name = "request", targetNamespace = "")
        UpdateDLPaymentStatusServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.ApplicationUpdateServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "extendLicense", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.ExtendLicense")
    @ResponseWrapper(localName = "extendLicenseResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.ExtendLicenseResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/extendLicenseRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/extendLicenseResponse")
    public ApplicationUpdateServiceResponse extendLicense(
        @WebParam(name = "request", targetNamespace = "")
        ApplicationUpdateServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetLearnerApplicationServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLearnerApplicationByCriteria", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetLearnerApplicationByCriteria")
    @ResponseWrapper(localName = "getLearnerApplicationByCriteriaResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetLearnerApplicationByCriteriaResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getLearnerApplicationByCriteriaRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getLearnerApplicationByCriteriaResponse")
    public GetLearnerApplicationServiceResponse getLearnerApplicationByCriteria(
        @WebParam(name = "request", targetNamespace = "")
        GetApplicationServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.SmsSendResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendSms", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.SendSms")
    @ResponseWrapper(localName = "sendSmsResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.SendSmsResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/sendSmsRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/sendSmsResponse")
    public SmsSendResponse sendSms(
        @WebParam(name = "request", targetNamespace = "")
        SmsSendRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetDlEnrollServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDlApplication", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetDlApplication")
    @ResponseWrapper(localName = "getDlApplicationResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetDlApplicationResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getDlApplicationRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getDlApplicationResponse")
    public GetDlEnrollServiceResponse getDlApplication(
        @WebParam(name = "request", targetNamespace = "")
        GetDlApplicationServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetForeignMissionShortNameResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getForeignMissionShortNames", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetForeignMissionShortNames")
    @ResponseWrapper(localName = "getForeignMissionShortNamesResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetForeignMissionShortNamesResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getForeignMissionShortNamesRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getForeignMissionShortNamesResponse")
    public GetForeignMissionShortNameResponse getForeignMissionShortNames(
        @WebParam(name = "request", targetNamespace = "")
        GetForeignMissionShortNameRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.ApplicationUpdateServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "applicationUpdate", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.ApplicationUpdate")
    @ResponseWrapper(localName = "applicationUpdateResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.ApplicationUpdateResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/applicationUpdateRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/applicationUpdateResponse")
    public ApplicationUpdateServiceResponse applicationUpdate(
        @WebParam(name = "request", targetNamespace = "")
        ApplicationUpdateServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetEnrolledApplicationResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPreEnrolledApplication", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetPreEnrolledApplication")
    @ResponseWrapper(localName = "getPreEnrolledApplicationResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetPreEnrolledApplicationResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getPreEnrolledApplicationRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getPreEnrolledApplicationResponse")
    public GetEnrolledApplicationResponse getPreEnrolledApplication(
        @WebParam(name = "request", targetNamespace = "")
        GetEnrolledApplicationRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetEnrollmentServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addPreEnrollment", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.AddPreEnrollment")
    @ResponseWrapper(localName = "addPreEnrollmentResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.AddPreEnrollmentResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/addPreEnrollmentRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/addPreEnrollmentResponse")
    public GetEnrollmentServiceResponse addPreEnrollment(
        @WebParam(name = "request", targetNamespace = "")
        GetEnrollmentServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetDlEnrollServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addDLEnrollment", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.AddDLEnrollment")
    @ResponseWrapper(localName = "addDLEnrollmentResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.AddDLEnrollmentResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/addDLEnrollmentRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/addDLEnrollmentResponse")
    public GetDlEnrollServiceResponse addDLEnrollment(
        @WebParam(name = "request", targetNamespace = "")
        GetDlEnrollServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetEnrollmentServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLoginApplication", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetLoginApplication")
    @ResponseWrapper(localName = "getLoginApplicationResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetLoginApplicationResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getLoginApplicationRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getLoginApplicationResponse")
    public GetEnrollmentServiceResponse getLoginApplication(
        @WebParam(name = "request", targetNamespace = "")
        GetApplicationServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetNationalityLookupServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNationalities", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetNationalities")
    @ResponseWrapper(localName = "getNationalitiesResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetNationalitiesResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getNationalitiesRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getNationalitiesResponse")
    public GetNationalityLookupServiceResponse getNationalities(
        @WebParam(name = "request", targetNamespace = "")
        GetNationalityLookupServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetDlEnrollServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValidateDlApplication", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetValidateDlApplication")
    @ResponseWrapper(localName = "getValidateDlApplicationResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetValidateDlApplicationResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getValidateDlApplicationRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getValidateDlApplicationResponse")
    public GetDlEnrollServiceResponse getValidateDlApplication(
        @WebParam(name = "request", targetNamespace = "")
        GetDlApplicationServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetForeignMissionServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllForeignMissionInSameCountryByMissionId", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetAllForeignMissionInSameCountryByMissionId")
    @ResponseWrapper(localName = "getAllForeignMissionInSameCountryByMissionIdResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetAllForeignMissionInSameCountryByMissionIdResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getAllForeignMissionInSameCountryByMissionIdRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getAllForeignMissionInSameCountryByMissionIdResponse")
    public GetForeignMissionServiceResponse getAllForeignMissionInSameCountryByMissionId(
        @WebParam(name = "request", targetNamespace = "")
        GetForeignMissionServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetEnrollmentServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValidateApplication", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetValidateApplication")
    @ResponseWrapper(localName = "getValidateApplicationResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetValidateApplicationResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getValidateApplicationRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getValidateApplicationResponse")
    public GetEnrollmentServiceResponse getValidateApplication(
        @WebParam(name = "request", targetNamespace = "")
        GetApplicationServiceRequest request);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRollNumber", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetRollNumber")
    @ResponseWrapper(localName = "getRollNumberResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetRollNumberResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getRollNumberRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getRollNumberResponse")
    public String getRollNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetForeignMissionServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getForeignMission", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetForeignMission")
    @ResponseWrapper(localName = "getForeignMissionResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetForeignMissionResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getForeignMissionRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getForeignMissionResponse")
    public GetForeignMissionServiceResponse getForeignMission(
        @WebParam(name = "request", targetNamespace = "")
        GetForeignMissionServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.service.GetLookupServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLookupByType", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetLookupByType")
    @ResponseWrapper(localName = "getLookupByTypeResponse", targetNamespace = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/", className = "com.service.GetLookupByTypeResponse")
    @Action(input = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getLookupByTypeRequest", output = "http://bean.enrollment.ws.preenrollment.hsdl.tigerit.com/EnrollmentServiceBeanService/getLookupByTypeResponse")
    public GetLookupServiceResponse getLookupByType(
        @WebParam(name = "request", targetNamespace = "")
        GetLookupServiceRequest request);

}
